language: cpp

install:
  - wget https://github.com/aitorSDL/vpl-xmlrpc-jail/tree/2.5.4/
  - tar xvf vpl-xmlrpc-jail-2.5.4.tar.gz
  - cd vpl-xmlrpc-jail-2.5.4
  - sudo make distcheck
  
script:
  - tests/test.sh
