language: cpp

install:
  - git clone git://github.com/aitorSDL/vpl-xmlrpc-jail.git
  - tar xvf vpl-xmlrpc-jail-2.5.4.tar.gz
  - cd vpl-xmlrpc-jail-2.5.4
  - sudo make distcheck
  
script:
  - tests/test.sh
