language: cpp

sudo: required

before_script:
  - chmod +x /home/travis/build/moodle/mod/vpl/tests/vpl_evaluate/test_vpl_evaluate.sh

install:
  - moodle-plugin-ci install

script:
  - /home/travis/build/moodle/mod/vpl/tests/vpl_evaluate/test_vpl_evaluate.sh
